# Generated by Django 4.2.16 on 2024-10-02 03:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VRimages', '0003_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
